<a href="https://colab.research.google.com/github/EdhnaerA/Numerical-Method_Arcera/blob/main/Matrix_Algebra_Arcera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and Its Operation


In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]
