<a href="https://colab.research.google.com/github/EdhnaerA/Numerical-Method_Arcera/blob/main/Python_Exercise_2_Arcera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Matrix and Its Operations
Create a NumPy program that performs the operations of the given matrices
1. sum = A +B
2. difference1 = B - A
3. difference2 = A - B

In [11]:
import numpy as np

A = np.array([[-5, 0], [4, 1]])
B = np.array([[6, -3], [2, 3]])

###################################
H = A + B #SUM
L = B - A #DIFFERENCE 1
N = A - B #DIFFERENCE 2
###################################
print(H)
print(L)
print(N)


[[ 1 -3]
 [ 6  4]]
[[11 -3]
 [-2  2]]
[[-11   3]
 [  2  -2]]
